export const extractPrompt = [
  "Extract student report card data into JSON. Use the mappingData provided in the user message for all ID lookups.",
  "",
  "## Output Format",
  "Return ONLY a raw JSON object (no markdown, no code fences) with EXACTLY these top-level keys:",
  '{ "studentData": {...}, "marksData": [...], "teachersRemark": {...}, "studentRatings": {...} }',
  "",
  "### studentData fields",
  "studentId: null, recordId: null, schoolId: null,",
  "admissionNo: number (from image), fullName: string,",
  "class: string (e.g. 'GRADE KA'), classId: number (from mappingData.classSection.classId),",
  "className: string (from mappingData.classSection.className), sectionId: number (from mappingData.classSection.sectionId),",
  "sectionName: string (from mappingData.classSection.sectionName),",
  "studentCategory: string (mapped from class: DAYCARE|NURSERY|GRADEK|LOWERBASIC|MIDDLEBASIC),",
  "  - Map 'CRECHE' or 'NURSERY' class -> 'NURSERY', 'LOWER BASIC' -> 'LOWERBASIC', 'MIDDLE BASIC' -> 'MIDDLEBASIC'.",
  "studentCategoryId: number (from mappingData.studentCategories, match by studentCategory name),",
  "term: string (from mappingData.examTypes.title), examTypeId: number (from mappingData.examTypes.id),",
  "attendance: { daysOpened: number, daysPresent: number, daysAbsent: number }",
  "  - daysPresent + daysAbsent MUST equal daysOpened",
  "",
  "### marksData fields (array, one entry per subject)",
  "Each item: { subjectCode, subjectName, subjectId (from mappingData.subjects),",
  "  examTitles: string[] (EXACTLY match the column headers in the image, e.g. ['CA1','CA2','HW','EXAM']),",
  "  marks: number[] (SAME ORDER as examTitles), total: number, grade: string (HTML span) }",
  "  - Transform 'H/W' or 'HW' header -> 'HOMEWORK' in examTitles.",
  "  - For DAYCARE: omit examTitles/marks/total/grade, include learningOutcome: string instead.",
  "",
  "### teachersRemark",
  '{ "comment": string | null, "note": string | null }',
  "",
  "### studentRatings (null if not present)",
  '{ "adherent_and_independent": number|null, "flexibility_and_creativity": number|null,',
  '  "meticulous": number|null, "neatness": number|null,',
  '  "overall_progress": number|null, "self_control_and_interaction": number|null }',
  "",
  "## Grade Labels",
  "EYFS (DAYCARE,NURSERY,GRADEK): 0-80:EMERGING(bg-purple-200), 81-90:EXPECTED(bg-blue-200), 91-100:EXCEEDING(bg-red-200).",
  "GRADERS (LOWERBASIC,MIDDLEBASIC): 0-69:E(bg-red-200), 70-76:D(bg-orange-200), 77-85:C(bg-yellow-200), 86-93:B(bg-blue-200), 94-100:A(bg-purple-200).",
  'HTML: \'<span class="{BG} text-violet-600 py-1 px-3 rounded-full text-xs">{LABEL}</span>\'',
  "",
  "Return ONLY the JSON object. No explanation, no markdown.",
].join("\n");
