services:
  edapex:
    image: ghcr.io/beznet22/edapex:latest
    pull_policy: always
    user: "${UID}:${GID}"
    expose:
      - 3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SIGN_SECRET=${JWT_SIGN_SECRET}
      - JWE_ENC_SECRET=${JWE_ENC_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - MASTRA_DB_URL=file:/app/storage/edapex-mastra.db
      - PUBLIC_ALLOW_ANONYMOUS_CHATS=${PUBLIC_ALLOW_ANONYMOUS_CHATS}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENCODE_API_KEY=${OPENCODE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - KIMCHI_API_KEY=${KIMCHI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
      - SMTP_TO=${SMTP_TO}
    volumes:
      - ${STORAGE_DIR}/workspaces:/app/.workspaces/
      - ${STORAGE_DIR}/storage:/app/storage/
      - ${STORAGE_DIR}/static:/app/static/
    restart: unless-stopped
