<script lang="ts">
  import type { Transcript } from "$lib/schema/transcript";

  interface Props {
    school: Transcript["school"];
    principalName: string;
  }

  let { school, principalName }: Props = $props();

  const generatedDate = $derived(
    new Date().toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
  );
</script>

<footer class="w-full mt-6 px-4 print:mt-12">
  <div class="grid grid-cols-2 gap-8 mt-12">
    <div class="text-center">
      <div class="border-t border-foreground/40 pt-2">
        <span
          class="print:bg-violet-900 uppercase btn btn-xs border print:text-slate-300 rounded-full"
        >
          Principal
        </span>
        <p class="text-xs print:text-slate-500 uppercase mt-1">
          {principalName}
        </p>
      </div>
    </div>

    <div class="text-center">
      <div class="border-t border-foreground/40 pt-2">
        <span
          class="print:bg-violet-900 uppercase btn btn-xs border print:text-slate-300 rounded-full"
        >
          Date Issued
        </span>
        <p class="text-xs print:text-slate-500 uppercase mt-1">
          {generatedDate}
        </p>
      </div>
    </div>
  </div>

  {#if school.email}
    <p class="text-[10px] text-center text-muted-foreground/60 mt-6 print:text-slate-500">
      Generated by EdApex · {school.email}
    </p>
  {/if}
</footer>