import { CredentialType } from "$lib/schema/chat-schema";

export const agentProviderMap: Record<string, CredentialType> = {
    "assessment": CredentialType.QWEN_CODE,
    "communicate": CredentialType.QWEN_CODE,
    "document": CredentialType.QWEN_CODE,
    "report": CredentialType.QWEN_CODE,
    // Future mappings
    "coding": CredentialType.GOOGLE_OAUTH,
    "default": CredentialType.QWEN_CODE
};

export type TaskType = 'title' | 'chat' | 'vision' | 'artifact';

export class ProviderRouter {
    private agentMap: Record<string, CredentialType> = agentProviderMap;

    /**
     * Route to the appropriate provider based on task type and agent.
     */
    route(task: TaskType, agentId?: string): CredentialType {
        switch (task) {
            case 'vision':
                // For vision tasks, we might prefer a specific provider if available
                // For now, let's default to the agent's provider or QWEN if it supports vision
                return this.getProviderForAgent(agentId);
            case 'title':
                // Titles can be generated by smaller/faster models
                return this.getProviderForAgent(agentId);
            case 'artifact':
                // Artifacts might need stronger models
                return this.getProviderForAgent(agentId);
            case 'chat':
            default:
                return this.getProviderForAgent(agentId);
        }
    }

    /**
     * Get the configured provider for a specific agent.
     */
    getProviderForAgent(agentId?: string): CredentialType {
        if (!agentId) return this.agentMap["default"];
        return this.agentMap[agentId] || this.agentMap["default"];
    }
}

export const providerRouter = new ProviderRouter();

export function getProviderType(agentId?: string): CredentialType {
    if (!agentId) return agentProviderMap["default"];
    return agentProviderMap[agentId] || agentProviderMap["default"];
}

export function getFallbackProvider(connectedTypes: CredentialType[]): CredentialType | null {
    if (connectedTypes.length === 0) return null;
    return connectedTypes[0];
}
